# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Documentation Request
description: Report incorrect or needed documentation
title: "[DOC]: "
labels: ["documentation", "status: needs-triage"]


body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation request!

  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this documentation request?
      options:
        - Critical (currently preventing usage)
        - High
        - Medium
        - Low (would be nice)
    validations:
      required: true

  - type: input
    id: correction_location
    attributes:
      label: Please provide a link or source to the relevant docs
      placeholder: "ex: https://github.com/nvidia/cutile-python/blob/main/README.md"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe the problems in the documentation
      placeholder: The documents say to use foo.func(args) however an AttributeError is thrown
    validations:
      required: true

  - type: textarea
    id: correction
    attributes:
      label: (Optional) Propose a correction
      placeholder: foo.func() was deprecated, replace documentation with foo.new_func()

  - type: checkboxes
    id: terms
    attributes:
      label: Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/NVIDIA/cutile-python/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow cuTile Python's contributing guidelines
          required: true
        - label: I have searched the [open documentation](https://github.com/nvidia/cutile-python/issues?q=is%3Aopen+is%3Aissue+label%3A%22documentation) and have found no duplicates for this documentation request
          required: true
