# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Questions
description: Raise an issue here if you don't know how to use cuTile Python
title: "[Usage]: "
labels: ["question", "status: needs-triage"]


body:
  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this question?
      options:
        - Critical (currently preventing usage)
        - High
        - Medium
        - Low (would be nice)
    validations:
      required: true

  - type: input
    id: question
    attributes:
      label: Please describe your question.
      placeholder: ""
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/NVIDIA/cutile-python/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow cuTile Python's contributing guidelines
          required: true
        - label: I have searched the [open question](https://github.com/nvidia/cutile-python/issues?q=is%3Aopen+is%3Aissue+label%3A%question) and have found no duplicates for this question
          required: true
